# Generated by Django 4.1.4 on 2023-01-07 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gradesheet',
            name='name',
            field=models.CharField(default='', max_length=50),
        ),
    ]
