# Generated by Django 4.1.4 on 2023-01-11 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_rename_result_gradesheet_results'),
    ]

    operations = [
        migrations.AddField(
            model_name='gradesheet',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
